name: New Service
description: Create a new service with IssueOps
title: "[New Service]: "
labels: new-service
body:
  - type: textarea
    attributes:
      label: Repo name
      description: Enter in the name of the new repository
      placeholder: <enter-repo-name-here>
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Repo visibility
      description: Please select the visibility for the new repository
      options:
        - private
        - internal
        - public
    validations:
      required: true
  - type: textarea
    attributes:
      label: Team Write Permissions
      description: Enter in the name of the team with write access
      placeholder: dev-team
  - type: textarea
    attributes:
      label: Team Admin Permissions
      description: Enter in the name of the team with admin access
      placeholder: admin-team
  - type: dropdown
    attributes:
      label: Enable issues
      description: Whether to enable issues on the repo or not
      options:
        - "yes"
        - "no"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Enable projects
      description: Whether to enable projects on the repo or not
      options:
        - label: "yes"
          required: true
  - type: dropdown
    attributes:
      label: Extra features
      description: What else do you want
      multiple: true
      options:
        - new repo
        - new pr
        - new issue
    validations:
      required: true
